on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          # Use of `github.token` instead of `secrets.GITHUB_TOKEN` allows
          # checks to be run manually from the PR
          token: ${{ github.token }}
          release-type: node

      - run: echo "Release created?... ${{ steps.release.outputs.release_created }}"

      # Steps below handle publication to NPM
      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npm test
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --provenance --access public
        if: ${{ steps.release.outputs.release_created }}
